### ISSUE TITLE
doMinikubeCheck is used but not defined

### ISSUE THREAD

**Issue by ozzieba** [apache-spark-on-k8s/spark-integration#33]
It appears that this method was removed from KubernetesSuite.scala[ a few days ago](
https://github.com/ifilonenko/spark-integration/commit/103d507b8f3a370411fe882b394c98bb65ba6fee#diff-b48f976007a97d5dc81f882566752cdd) , along with all but [one](https://github.com/apache-spark-on-k8s/spark-integration/blob/master/integration-test/src/test/scala/org/apache/spark/deploy/k8s/integrationtest/KubernetesSuite.scala#L106
) of its usages. This line should presumably be removed as well.

**Comment by liyinan926** [comment]
See #32.

**Comment by foxish** [comment]
This has been fixed in https://github.com/apache-spark-on-k8s/spark-integration/pull/34
