### ISSUE TITLE
Set up Pepperdata Jenkins jobs for integration tests

### ISSUE THREAD

**Issue by kimoonkim** [apache-spark-on-k8s/spark-integration#5]
Discuss and document how we set up Pepperdata Jenkins jobs for integration tests.

We have set up a chain of 2 Jenkins jobs on the [Pepperdata Jenkins](http://spark-k8s-jenkins.pepperdata.org:8080/) site. The jobs are under the [upstream spark view](http://spark-k8s-jenkins.pepperdata.org:8080/view/upstream%20spark/):

1. The  [SCHEDULED-make-spark-distribution](http://spark-k8s-jenkins.pepperdata.org:8080/view/upstream%20spark/job/SCHEDULED-make-spark-distribution/) job runs every 3 hours. It fetches code from the [upstream spark repo](https://github.com/apache/spark/) and builds a distribution tarball. When done, it triggers the second Job as a post-build step.
1. The triggered [spark-integration](http://spark-k8s-jenkins.pepperdata.org:8080/view/upstream%20spark/job/scheduled-spark-integration/) job starts by copying the distribution tarball from the first job. It also copies `Dockerfile`s. Then it will fetch integration code from this [integration-test repo](https://github.com/apache-spark-on-k8s/spark-integration) and run test against the distribution tarball.

We have also set up another Jenkins build chain for PR triggered builds for upstream targetting changes. The process works like the following:
1. For each upstreaming PR, the author will send another twin PR to our [Spark fork](https://github.com/apache-spark-on-k8s/spark) master branch from the same source branch. An example twin PR is apache-spark-on-k8s/spark#582.
1. The twin PR will trigger the first Jenkins job in the PR build chain, [PR-make-spark-distribution](http://spark-k8s-jenkins.pepperdata.org:8080/view/upstream%20spark/job/PR-make-spark-distribution/), which will build a distribution tarball of the source code in the PR. The job is configured to react only to the master branch of our fork. After the tarball is built, the second Jenkins job will be triggered.
1. The [second Jenkins job](http://spark-k8s-jenkins.pepperdata.org:8080/view/upstream%20spark/job/pr-spark-integration/) copies the tarball from the first job and run integration tests using the test code in our [integration-test repo](https://github.com/apache-spark-on-k8s/spark-integration).
1. The two Jenkins jobs will post build status in the twin PR in our fork.
1. When the upstreaming PR is merged, the author will simply close the twin PR in our Spark fork.

**Comment by kimoonkim** [comment]
We expect #3 to be merged soon and used by this setup.

**Comment by kimoonkim** [comment]
@foxish @liyinan926 How do we want to be notified by the Jenkins job in case integration tests fail?For instance, posting to our slack channel is a possibility. See https://wiki.jenkins.io/display/JENKINS/Slack+Plugin.

**Comment by liyinan926** [comment]
@kimoonkim either email notification or Slack notification works for me.

**Comment by liyinan926** [comment]
Thanks, @kimoonkim SGTM.

**Comment by kimoonkim** [comment]
Cool. Done.

**Comment by foxish** [comment]
Looks like email alerts are working. However, this setup didn't catch the regression in https://github.com/apache/spark/pull/20051. Is that because the dockerfile build flow is still separate? @kimoonkim PTAL.

**Comment by foxish** [comment]
The regression was that upstream cannot build the docker images at all - because the paths weren't correct.

**Comment by kimoonkim** [comment]
>  However, this setup didn't catch the regression which I just fixed in apache/spark#20051. Is that because the dockerfile build is still separate? @kimoonkim PTAL.
> The regression was that upstream could not build the docker images at all - because the paths weren't correct.

The integration test uses [SparkDockerImageBuilder](https://github.com/apache-spark-on-k8s/spark-integration/blob/master/integration-test/src/test/scala/org/apache/spark/deploy/k8s/integrationtest/docker/SparkDockerImageBuilder.scala) for backing Docker images. Jenkins runs have been fine because the setup was doing the right thing. It copies `Dockerfiles` from the source repo and puts them in the right place that `SparkDockerImageBuilder` expects:
```
          <execution>
            <!-- TODO: Remove this hack once the upstream is fixed -->
            <id>copy-dockerfiles-if-missing</id>
            <phase>pre-integration-test</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <configuration>
              <workingDirectory>${project.build.directory}/spark-distro</workingDirectory>
              <executable>/bin/sh</executable>
              <arguments>
                <argument>-c</argument>
                <argument>test -d dockerfiles || cp -pr ${spark-dockerfiles-dir} dockerfiles</argument>
              </arguments>
            </configuration>
          </execution>
```
Above, `${spark-dockerfiles-dir}` has been pointing to the right dir that your fix is setting now, `resource-managers/kubernetes/docker/src/main/dockerfiles/`. And we copied them to `target/spark-distro/dockerfiles`. (Now, with your fix in Dockerfiles, this will be broken :-))

We had to do this because the upstream `make-distribution.sh` does not copy Dockerfiles yet. What's our status on `make-distribution.sh` fix? We need to determine if Dockerfiles will be part of the distro, and where exactly they would show up inside the tarball.

**Comment by foxish** [comment]
Ah, we copied them to `dockerfiles`, that's why. Okay, makes sense.
The `make-distribution.sh` fix is checked in now. https://github.com/apache/spark/blob/master/dev/make-distribution.sh#L177-L181

**Comment by kimoonkim** [comment]
Ah, good. Then we should probably kill the copy step in pom.xml as well as the copy-artifact setup in Jenkins. I'll work on it.

**Comment by kimoonkim** [comment]
FYI, we are also setting up PR triggered Jenkins builds for upstream targetting changes. The idea is to have a twin PR in our fork for each upstreaming PR, and trigger a Jenkins build against the PR in our fork.

There is a challenge in the fact that each build has two Jenkins jobs dealing with two repos. The first job for building spark distro tarball and the second job for running integration tests. We want the second job to update the spark fork PR with the result. This needs some config tweaks. See https://github.com/jenkinsci/ghprb-plugin/issues/326 for details.

**Comment by kimoonkim** [comment]
> FYI, we are also setting up PR triggered Jenkins builds for upstream targetting changes.

The PR support works now, as evidenced by https://github.com/apache-spark-on-k8s/spark/pull/582.

**Comment by foxish** [comment]
Excellent. We can close this now. Thanks Kimoon!

**Comment by kimoonkim** [comment]
Closing. Updated the issue description with the story for the PR build chain.
